/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/plans/{planId}/import/sessions/{sid}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setMapping"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setHeader"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setDecisions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["shutdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForSeason"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForPlan"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/persons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/participants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch: operations["update_3"];
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["validate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["columns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/field-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForPlan_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constraint-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ColumnMappingDto: {
            /** Format: int32 */
            columnIndex?: number;
            target?: string;
        };
        MappingRequest: {
            sheet?: string;
            mappings?: components["schemas"]["ColumnMappingDto"][];
        };
        MappingResponse: {
            sheet?: string;
            mappings?: components["schemas"]["ColumnMappingDto"][];
        };
        HeaderRequest: {
            sheet?: string;
            /** Format: int32 */
            headerRowIndex?: number;
        };
        HeaderResponse: {
            sheet?: string;
            /** Format: int32 */
            headerRowIndex?: number;
        };
        DecisionDto: {
            action?: string;
            personId?: string;
        };
        CreateSeasonPlanRequest: {
            name?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            status?: string;
        };
        SeasonPlan: {
            id?: string;
            name?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateActivityPlanRequest: {
            name?: string;
            category?: string;
            status?: string;
            /** Format: int32 */
            defaultGroupTargetSize?: number;
            /** Format: int32 */
            defaultGroupMinSize?: number;
            /** Format: int32 */
            defaultGroupMaxSize?: number;
        };
        ActivityPlan: {
            id?: string;
            seasonPlanId?: string;
            name?: string;
            category?: string;
            status?: string;
            /** Format: int32 */
            defaultGroupTargetSize?: number;
            /** Format: int32 */
            defaultGroupMinSize?: number;
            /** Format: int32 */
            defaultGroupMaxSize?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateParticipantProfileRequest: {
            personId?: string;
            /** Format: double */
            rankingPoints?: number;
            rankingSource?: string;
            previousGroupName?: string;
            /** Format: double */
            previousGroupLevel?: number;
            /** Format: double */
            estimatedLevel?: number;
            /** Format: double */
            levelConfidence?: number;
            /** Format: double */
            manualLevelScore?: number;
            importedComment?: string;
            internalNote?: string;
            manualReviewFlag?: boolean;
            waitlisted?: boolean;
        };
        ParticipantProfile: {
            id?: string;
            personId?: string;
            activityPlanId?: string;
            /** Format: double */
            rankingPoints?: number;
            rankingSource?: string;
            previousGroupName?: string;
            /** Format: double */
            previousGroupLevel?: number;
            /** Format: double */
            estimatedLevel?: number;
            /** Format: double */
            levelConfidence?: number;
            /** Format: double */
            manualLevelScore?: number;
            importedComment?: string;
            internalNote?: string;
            manualReviewFlag?: boolean;
            waitlisted?: boolean;
        };
        CreatedSession: {
            sessionId?: string;
            sheets?: components["schemas"]["SheetSummary"][];
        };
        SheetSummary: {
            name?: string;
            /** Format: int32 */
            rowCount?: number;
            suggestedTemplateId?: string;
            suggestedTemplateName?: string;
        };
        CommitRequest: {
            saveAsTemplate?: boolean;
            templateName?: string;
        };
        CommitResult: {
            /** Format: int32 */
            imported?: number;
            /** Format: int32 */
            skipped?: number;
            warnings?: string[];
            importRunId?: string;
            savedTemplateId?: string;
        };
        CreatePersonRequest: {
            firstName?: string;
            lastName?: string;
            displayName?: string;
            email?: string;
            phone?: string;
            externalId?: string;
            canBeParticipant?: boolean;
            canBeCoach?: boolean;
            notes?: string;
        };
        Person: {
            id?: string;
            firstName?: string;
            lastName?: string;
            displayName?: string;
            email?: string;
            phone?: string;
            externalId?: string;
            canBeParticipant?: boolean;
            canBeCoach?: boolean;
            notes?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateSeasonPlanRequest: {
            name?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            status?: string;
        };
        UpdateActivityPlanRequest: {
            name?: string;
            category?: string;
            status?: string;
            /** Format: int32 */
            defaultGroupTargetSize?: number;
            /** Format: int32 */
            defaultGroupMinSize?: number;
            /** Format: int32 */
            defaultGroupMaxSize?: number;
        };
        UpdatePersonRequest: {
            firstName?: string;
            lastName?: string;
            displayName?: string;
            email?: string;
            phone?: string;
            externalId?: string;
            canBeParticipant?: boolean;
            canBeCoach?: boolean;
            notes?: string;
        };
        UpdateParticipantProfileRequest: {
            /** Format: double */
            rankingPoints?: number;
            rankingSource?: string;
            previousGroupName?: string;
            /** Format: double */
            previousGroupLevel?: number;
            /** Format: double */
            estimatedLevel?: number;
            /** Format: double */
            levelConfidence?: number;
            /** Format: double */
            manualLevelScore?: number;
            importedComment?: string;
            internalNote?: string;
            manualReviewFlag?: boolean;
            waitlisted?: boolean;
        };
        PersonMatchProposal: {
            existingPersonId?: string;
            /** @enum {string} */
            matchBasis?: "EXTERNAL_ID_EXACT" | "EMAIL_EXACT" | "PHONE_EXACT" | "NAME_EXACT" | "NAME_SIMILAR";
            /** Format: double */
            confidence?: number;
        };
        RowValidationResult: {
            /** Format: int32 */
            rowIndex?: number;
            /** @enum {string} */
            status?: "OK" | "WARN" | "SKIP";
            reasons?: string[];
            matchProposals?: components["schemas"]["PersonMatchProposal"][];
        };
        ValidateResponse: {
            rows?: components["schemas"]["RowValidationResult"][];
            /** Format: int32 */
            totalRows?: number;
            /** Format: int32 */
            okCount?: number;
            /** Format: int32 */
            warnCount?: number;
            /** Format: int32 */
            skipCount?: number;
        };
        PreviewResponse: {
            sheet?: string;
            /** Format: int32 */
            headerRowIndex?: number;
            /** Format: int32 */
            rowCount?: number;
            rows?: string[][];
        };
        ColumnInfo: {
            /** Format: int32 */
            columnIndex?: number;
            headerText?: string;
            sampleValues?: string[];
            suggestedTarget?: string;
        };
        ColumnsResponse: {
            sheet?: string;
            /** Format: int32 */
            headerRowIndex?: number;
            columns?: components["schemas"]["ColumnInfo"][];
        };
        FieldDefinition: {
            id?: string;
            activityPlanId?: string;
            key?: string;
            label?: string;
            fieldType?: string;
            isStandard?: boolean;
            storageKind?: string;
            columnName?: string;
            affectsOptimization?: boolean;
            constraintType?: string;
            hardOrSoft?: string;
            /** Format: int32 */
            weight?: number;
            direction?: string;
            explanationText?: string;
            optionsJson?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        ImportTemplate: {
            id?: string;
            name?: string;
            headerHash?: string;
            mappingJson?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ConstraintDefinition: {
            key?: string;
            label?: string;
            description?: string;
            constraintCategory?: string;
            /** Format: int32 */
            defaultWeight?: number;
            hardOrSoft?: string;
            enabled?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MappingResponse"];
                };
            };
        };
    };
    setHeader: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeaderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HeaderResponse"];
                };
            };
        };
    };
    setDecisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["DecisionDto"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["DecisionDto"];
                    };
                };
            };
        };
    };
    shutdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeasonPlan"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSeasonPlanRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeasonPlan"];
                };
            };
        };
    };
    listForSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPlan"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityPlanRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPlan"];
                };
            };
        };
    };
    listForPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipantProfile"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateParticipantProfileRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipantProfile"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSession"];
                };
            };
        };
    };
    commit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommitResult"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Person"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Person"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeasonPlan"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSeasonPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeasonPlan"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPlan"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivityPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPlan"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Person"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePersonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Person"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipantProfile"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateParticipantProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipantProfile"];
                };
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ValidateResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query: {
                sheet: string;
                rows?: number;
            };
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PreviewResponse"];
                };
            };
        };
    };
    columns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnsResponse"];
                };
            };
        };
    };
    listForPlan_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FieldDefinition"][];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportTemplate"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConstraintDefinition"][];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
