/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/plans/{planId}/time-slots/{slotId}/courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setCourts"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/participants/{pid}/field-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setMapping"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/header": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setHeader"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setDecisions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/constraint-weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/coaches/{id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAvailability"];
        put: operations["putAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/coaches/{cid}/field-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["put_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["shutdown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{seasonId}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForSeason"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/time-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForPlan"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForPlan_1"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/participants/recompute-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recomputeLevels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/field-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForPlan_2"];
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/comments/anonymize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["anonymizeAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/coaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForPlan_3"];
        put?: never;
        post: operations["create_6"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_7"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["create_8"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/training-blocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateActive"];
        trace?: never;
    };
    "/api/time-slots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/seasons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch: operations["update_3"];
        trace?: never;
    };
    "/api/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_5"];
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch: operations["update_4"];
        trace?: never;
    };
    "/api/persons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_6"];
        put?: never;
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch: operations["update_5"];
        trace?: never;
    };
    "/api/participants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_7"];
        put?: never;
        post?: never;
        delete: operations["delete_5"];
        options?: never;
        head?: never;
        patch: operations["update_6"];
        trace?: never;
    };
    "/api/field-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_6"];
        options?: never;
        head?: never;
        patch: operations["update_7"];
        trace?: never;
    };
    "/api/courts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_8"];
        put?: never;
        post?: never;
        delete: operations["delete_7"];
        options?: never;
        head?: never;
        patch: operations["update_8"];
        trace?: never;
    };
    "/api/coaches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_9"];
        put?: never;
        post?: never;
        delete: operations["delete_8"];
        options?: never;
        head?: never;
        patch: operations["update_9"];
        trace?: never;
    };
    "/api/plans/{planId}/training-blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listForPlan_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["validate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["columns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCapacity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constraint-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/participants/{pid}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteOne"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{planId}/import/sessions/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SetCourtsRequest: {
            /** Format: int32 */
            count?: number;
        };
        TrainingBlockView: {
            id?: string;
            timeSlotId?: string;
            courtId?: string;
            courtName?: string;
            activityPlanId?: string;
            active?: boolean;
            locked?: boolean;
        };
        JsonNode: unknown;
        FieldValueView: {
            fieldDefinitionId?: string;
            key?: string;
            label?: string;
            fieldType?: string;
            value?: components["schemas"]["JsonNode"];
        };
        ColumnMappingDto: {
            /** Format: int32 */
            columnIndex?: number;
            target?: string;
        };
        MappingRequest: {
            sheet?: string;
            mappings?: components["schemas"]["ColumnMappingDto"][];
        };
        MappingResponse: {
            sheet?: string;
            mappings?: components["schemas"]["ColumnMappingDto"][];
        };
        HeaderRequest: {
            sheet?: string;
            /** Format: int32 */
            headerRowIndex?: number;
        };
        HeaderResponse: {
            sheet?: string;
            /** Format: int32 */
            headerRowIndex?: number;
        };
        DecisionDto: {
            action?: string;
            personId?: string;
        };
        ConstraintWeightOverrideRequest: {
            key?: string;
            hardOrSoft?: string;
            /** Format: int32 */
            weight?: number;
            enabled?: boolean;
        };
        ConstraintWeightView: {
            key?: string;
            label?: string;
            description?: string;
            constraintCategory?: string;
            hardOrSoft?: string;
            /** Format: int32 */
            weight?: number;
            enabled?: boolean;
            overridden?: boolean;
        };
        AvailabilityEntry: {
            timeSlotId?: string;
            kind?: string;
        };
        CreateVenueRequest: {
            name?: string;
            notes?: string;
        };
        Court: {
            id?: string;
            venueId?: string;
            name?: string;
            active?: boolean;
            notes?: string;
        };
        VenueView: {
            id?: string;
            name?: string;
            notes?: string;
            courts?: components["schemas"]["Court"][];
        };
        CreateSeasonPlanRequest: {
            name?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            status?: string;
        };
        SeasonPlan: {
            id?: string;
            name?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateActivityPlanRequest: {
            name?: string;
            category?: string;
            status?: string;
            /** Format: int32 */
            defaultGroupTargetSize?: number;
            /** Format: int32 */
            defaultGroupMinSize?: number;
            /** Format: int32 */
            defaultGroupMaxSize?: number;
        };
        ActivityPlan: {
            id?: string;
            seasonPlanId?: string;
            name?: string;
            category?: string;
            status?: string;
            /** Format: int32 */
            defaultGroupTargetSize?: number;
            /** Format: int32 */
            defaultGroupMinSize?: number;
            /** Format: int32 */
            defaultGroupMaxSize?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateTimeSlotRequest: {
            dayOfWeek?: string;
            date?: string;
            startTime?: string;
            endTime?: string;
            label?: string;
        };
        TimeSlot: {
            id?: string;
            activityPlanId?: string;
            dayOfWeek?: string;
            date?: string;
            startTime?: string;
            endTime?: string;
            /** Format: int32 */
            durationMinutes?: number;
            label?: string;
        };
        CreateParticipantProfileRequest: {
            personId?: string;
            /** Format: double */
            rankingPoints?: number;
            rankingSource?: string;
            previousGroupName?: string;
            /** Format: double */
            previousGroupLevel?: number;
            /** Format: double */
            estimatedLevel?: number;
            /** Format: double */
            levelConfidence?: number;
            /** Format: double */
            manualLevelScore?: number;
            importedComment?: string;
            internalNote?: string;
            manualReviewFlag?: boolean;
            waitlisted?: boolean;
        };
        ParticipantProfile: {
            id?: string;
            personId?: string;
            activityPlanId?: string;
            /** Format: double */
            rankingPoints?: number;
            rankingSource?: string;
            previousGroupName?: string;
            /** Format: double */
            previousGroupLevel?: number;
            /** Format: double */
            estimatedLevel?: number;
            /** Format: double */
            levelConfidence?: number;
            /** Format: double */
            manualLevelScore?: number;
            importedComment?: string;
            internalNote?: string;
            manualReviewFlag?: boolean;
            waitlisted?: boolean;
        };
        RecomputeLevelsResult: {
            /** Format: int32 */
            recomputedCount?: number;
        };
        CreatedSession: {
            sessionId?: string;
            sheets?: components["schemas"]["SheetSummary"][];
        };
        SheetSummary: {
            name?: string;
            /** Format: int32 */
            rowCount?: number;
            suggestedTemplateId?: string;
            suggestedTemplateName?: string;
        };
        CommitRequest: {
            saveAsTemplate?: boolean;
            templateName?: string;
        };
        CommitResult: {
            /** Format: int32 */
            imported?: number;
            /** Format: int32 */
            skipped?: number;
            warnings?: string[];
            importRunId?: string;
            savedTemplateId?: string;
        };
        CreateFieldDefinitionRequest: {
            key?: string;
            label?: string;
            fieldType?: string;
            affectsOptimization?: boolean;
            constraintType?: string;
            hardOrSoft?: string;
            /** Format: int32 */
            weight?: number;
            direction?: string;
            explanationText?: string;
            optionsJson?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        FieldDefinition: {
            id?: string;
            activityPlanId?: string;
            key?: string;
            label?: string;
            fieldType?: string;
            isStandard?: boolean;
            storageKind?: string;
            columnName?: string;
            affectsOptimization?: boolean;
            constraintType?: string;
            hardOrSoft?: string;
            /** Format: int32 */
            weight?: number;
            direction?: string;
            explanationText?: string;
            optionsJson?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        AnonymizeRequest: {
            confirm?: boolean;
        };
        AnonymizeResult: {
            /** Format: int32 */
            clearedCount?: number;
        };
        CreateCoachRequest: {
            personId?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
            /** Format: double */
            coachLevel?: number;
            /** Format: double */
            canCoachMinLevel?: number;
            /** Format: double */
            canCoachMaxLevel?: number;
            /** Format: int32 */
            maxGroupsPerDay?: number;
            /** Format: int32 */
            maxGroupsPerWeek?: number;
            canAlsoTrainAsParticipant?: boolean;
            notes?: string;
        };
        CoachProfile: {
            id?: string;
            personId?: string;
            activityPlanId?: string;
            /** Format: double */
            coachLevel?: number;
            /** Format: double */
            canCoachMinLevel?: number;
            /** Format: double */
            canCoachMaxLevel?: number;
            /** Format: int32 */
            maxGroupsPerDay?: number;
            /** Format: int32 */
            maxGroupsPerWeek?: number;
            canAlsoTrainAsParticipant?: boolean;
            notes?: string;
        };
        CreatePersonRequest: {
            firstName?: string;
            lastName?: string;
            displayName?: string;
            email?: string;
            phone?: string;
            externalId?: string;
            canBeParticipant?: boolean;
            canBeCoach?: boolean;
            notes?: string;
        };
        Person: {
            id?: string;
            firstName?: string;
            lastName?: string;
            displayName?: string;
            email?: string;
            phone?: string;
            externalId?: string;
            canBeParticipant?: boolean;
            canBeCoach?: boolean;
            notes?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateCourtRequest: {
            venueId?: string;
            name?: string;
            active?: boolean;
            notes?: string;
        };
        UpdateVenueRequest: {
            name?: string;
            notes?: string;
        };
        UpdateTrainingBlockRequest: {
            active?: boolean;
        };
        UpdateSeasonPlanRequest: {
            name?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            status?: string;
        };
        UpdateActivityPlanRequest: {
            name?: string;
            category?: string;
            status?: string;
            /** Format: int32 */
            defaultGroupTargetSize?: number;
            /** Format: int32 */
            defaultGroupMinSize?: number;
            /** Format: int32 */
            defaultGroupMaxSize?: number;
        };
        UpdatePersonRequest: {
            firstName?: string;
            lastName?: string;
            displayName?: string;
            email?: string;
            phone?: string;
            externalId?: string;
            canBeParticipant?: boolean;
            canBeCoach?: boolean;
            notes?: string;
        };
        UpdateFieldDefinitionRequest: {
            label?: string;
            affectsOptimization?: boolean;
            constraintType?: string;
            hardOrSoft?: string;
            /** Format: int32 */
            weight?: number;
            direction?: string;
            explanationText?: string;
            optionsJson?: string;
            /** Format: int32 */
            sortOrder?: number;
        };
        UpdateCourtRequest: {
            name?: string;
            active?: boolean;
            notes?: string;
        };
        SlotBlocksView: {
            timeSlot?: components["schemas"]["TimeSlot"];
            blocks?: components["schemas"]["TrainingBlockView"][];
        };
        PersonMatchProposal: {
            existingPersonId?: string;
            /** @enum {string} */
            matchBasis?: "EXTERNAL_ID_EXACT" | "EMAIL_EXACT" | "PHONE_EXACT" | "NAME_EXACT" | "NAME_SIMILAR";
            /** Format: double */
            confidence?: number;
        };
        RowValidationResult: {
            /** Format: int32 */
            rowIndex?: number;
            /** @enum {string} */
            status?: "OK" | "WARN" | "SKIP";
            reasons?: string[];
            matchProposals?: components["schemas"]["PersonMatchProposal"][];
        };
        ValidateResponse: {
            rows?: components["schemas"]["RowValidationResult"][];
            /** Format: int32 */
            totalRows?: number;
            /** Format: int32 */
            okCount?: number;
            /** Format: int32 */
            warnCount?: number;
            /** Format: int32 */
            skipCount?: number;
        };
        PreviewResponse: {
            sheet?: string;
            /** Format: int32 */
            headerRowIndex?: number;
            /** Format: int32 */
            rowCount?: number;
            rows?: string[][];
        };
        ColumnInfo: {
            /** Format: int32 */
            columnIndex?: number;
            headerText?: string;
            sampleValues?: string[];
            suggestedTarget?: string;
        };
        ColumnsResponse: {
            sheet?: string;
            /** Format: int32 */
            headerRowIndex?: number;
            columns?: components["schemas"]["ColumnInfo"][];
        };
        CapacityResponse: {
            /** Format: int32 */
            participantCount?: number;
            /** Format: int32 */
            waitlistedCount?: number;
            /** Format: int32 */
            activeTrainingBlockCount?: number;
            /** Format: int32 */
            targetGroupSize?: number;
            /** Format: int32 */
            maxGroupSize?: number;
            /** Format: int32 */
            targetCapacity?: number;
            /** Format: int32 */
            maxCapacity?: number;
            waitlistRisk?: string;
            waitlistMessage?: string;
            /** Format: int32 */
            coachCount?: number;
            /** Format: int32 */
            groupsRequiringCoachEstimate?: number;
            coachShortageRisk?: boolean;
            coachShortageMessage?: string;
            perTimeSlot?: components["schemas"]["TimeSlotCapacityView"][];
        };
        TimeSlotCapacityView: {
            timeSlotId?: string;
            label?: string;
            /** Format: int32 */
            activeBlockCount?: number;
            /** Format: int32 */
            coachesAvailableCount?: number;
            /** Format: int32 */
            coachesPreferredCount?: number;
        };
        ImportTemplate: {
            id?: string;
            name?: string;
            headerHash?: string;
            mappingJson?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ConstraintDefinition: {
            key?: string;
            label?: string;
            description?: string;
            constraintCategory?: string;
            /** Format: int32 */
            defaultWeight?: number;
            hardOrSoft?: string;
            enabled?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setCourts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                slotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCourtsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrainingBlockView"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FieldValueView"][];
                };
            };
        };
    };
    put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["JsonNode"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FieldValueView"][];
                };
            };
        };
    };
    setMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MappingResponse"];
                };
            };
        };
    };
    setHeader: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeaderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HeaderResponse"];
                };
            };
        };
    };
    setDecisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["DecisionDto"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["DecisionDto"];
                    };
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConstraintWeightView"][];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstraintWeightOverrideRequest"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConstraintWeightView"][];
                };
            };
        };
    };
    getAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AvailabilityEntry"][];
                };
            };
        };
    };
    putAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AvailabilityEntry"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AvailabilityEntry"][];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FieldValueView"][];
                };
            };
        };
    };
    put_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["JsonNode"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FieldValueView"][];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVenueRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueView"];
                };
            };
        };
    };
    shutdown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeasonPlan"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSeasonPlanRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeasonPlan"];
                };
            };
        };
    };
    listForSeason: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPlan"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                seasonId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityPlanRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPlan"];
                };
            };
        };
    };
    listForPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TimeSlot"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTimeSlotRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TimeSlot"];
                };
            };
        };
    };
    listForPlan_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipantProfile"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateParticipantProfileRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipantProfile"];
                };
            };
        };
    };
    recomputeLevels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecomputeLevelsResult"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreatedSession"];
                };
            };
        };
    };
    commit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommitResult"];
                };
            };
        };
    };
    listForPlan_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FieldDefinition"][];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFieldDefinitionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FieldDefinition"];
                };
            };
        };
    };
    anonymizeAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnonymizeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnonymizeResult"];
                };
            };
        };
    };
    listForPlan_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CoachProfile"][];
                };
            };
        };
    };
    create_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCoachRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CoachProfile"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Person"][];
                };
            };
        };
    };
    create_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Person"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                venueId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Court"][];
                };
            };
        };
    };
    create_8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourtRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Court"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueView"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVenueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VenueView"];
                };
            };
        };
    };
    updateActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTrainingBlockRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrainingBlockView"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TimeSlot"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["JsonNode"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TimeSlot"];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeasonPlan"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSeasonPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeasonPlan"];
                };
            };
        };
    };
    get_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPlan"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivityPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityPlan"];
                };
            };
        };
    };
    get_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Person"];
                };
            };
        };
    };
    delete_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePersonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Person"];
                };
            };
        };
    };
    get_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipantProfile"];
                };
            };
        };
    };
    delete_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["JsonNode"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ParticipantProfile"];
                };
            };
        };
    };
    delete_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFieldDefinitionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FieldDefinition"];
                };
            };
        };
    };
    get_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Court"];
                };
            };
        };
    };
    delete_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCourtRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Court"];
                };
            };
        };
    };
    get_9: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CoachProfile"];
                };
            };
        };
    };
    delete_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_9: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: components["schemas"]["JsonNode"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CoachProfile"];
                };
            };
        };
    };
    listForPlan_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SlotBlocksView"][];
                };
            };
        };
    };
    validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ValidateResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query: {
                sheet: string;
                rows?: number;
            };
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PreviewResponse"];
                };
            };
        };
    };
    columns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ColumnsResponse"];
                };
            };
        };
    };
    getCapacity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CapacityResponse"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportTemplate"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConstraintDefinition"][];
                };
            };
        };
    };
    deleteOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
